# Generated by Django 4.0.4 on 2022-05-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('author', models.CharField(default='', max_length=128)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
