# Generated by Django 4.0.4 on 2022-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(default='', max_length=128),
        ),
    ]
