# Generated by Django 4.0.4 on 2022-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslitapp', '0003_post_listingtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='notes',
            new_name='imageid',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
